version: '3.0'

services:
  development:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    ports:
     - "5000:5000"
    volumes:
     - .:/development

  production:
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    ports:
     - "80:80"
    volumes:
     - .:/production