name: Code Integration Check

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install and build dependencies
        run: yarn install --frozen-lockfile
  
  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install and build dependencies
        run: yarn install --frozen-lockfile
      - name: Run lint test
        run: |
          yarn eslint ./src
  
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install and build dependencies
        run: yarn install --frozen-lockfile
      - name: Run test
        run: |
          yarn test --passWithNoTests